<Project Sdk="Aspire.AppHost.Sdk/13.5.4">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>6a020968-c4c8-4d97-9b38-bc5707092ce5</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\JwtAuthDotnet9\JwtAuthDotnet9.csproj" />
  </ItemGroup>

</Project>
